import type { SyncContext } from './sync-repository-types'
import { readdir, writeFile } from 'node:fs/promises'
import { join } from 'pathe'
import { pathExists } from '../utils/fs'

export async function generateIndex(context: SyncContext): Promise<void> {
  const lines: string[] = []
  const dir = context.storageDirAbsolute

  lines.push('# GitHub Repository Mirror Index\n')
  lines.push(`**Repository**: ${context.repoSlug}`)
  lines.push(`**Last Synced**: ${new Date().toISOString()}\n`)
  lines.push('---\n')

  lines.push('## Quick Navigation\n')

  const sections: Array<{ title: string, file: string, dir?: string, desc: string }> = [
    { title: 'Repository Metadata', file: 'metadata.json', desc: 'Topics, features, labels, milestones, security' },
    { title: 'Issues', file: 'issues.md', dir: 'issues', desc: 'Open and closed issues with comments' },
    { title: 'Pull Requests', file: 'pulls.md', dir: 'pulls', desc: 'PRs with reviews, commits, and patches' },
    { title: 'Discussions', file: 'discussions.md', dir: 'discussions', desc: 'Community discussions by category' },
    { title: 'Wiki', file: 'wiki.md', dir: 'wiki', desc: 'Wiki pages' },
    { title: 'Releases', file: 'releases.md', dir: 'releases', desc: 'Release notes and tags' },
    { title: 'Merge Queue', file: 'merge-queue.md', desc: 'Current merge queue state' },
    { title: 'Workflows', file: 'workflows.md', desc: 'Recent GitHub Actions runs' },
    { title: 'CODEOWNERS', file: 'CODEOWNERS', desc: 'Code ownership rules' },
  ]

  for (const section of sections) {
    const filePath = join(dir, section.file)
    const dirPath = section.dir ? join(dir, section.dir) : null

    const fileExists = await pathExists(filePath)
    const dirExists = dirPath ? await pathExists(dirPath) : false

    if (fileExists || dirExists) {
      lines.push(`### ${section.title}`)
      lines.push(`*${section.desc}*\n`)

      if (fileExists)
        lines.push(`- Index: [\`${section.file}\`](./${section.file})`)

      if (dirExists) {
        try {
          const files = await readdir(dirPath!)
          const count = files.filter(f => f.endsWith('.md') || f.endsWith('.json') || f.endsWith('.patch')).length
          if (count > 0)
            lines.push(`- Directory: [\`${section.dir}/\`](./${section.dir}/) (${count} files)`)
        }
        catch {
          // ignore
        }
      }

      lines.push('')
    }
  }

  lines.push('---\n')
  lines.push('## What\'s Synced\n')
  lines.push('This mirror includes:\n')
  lines.push('- ✅ Issues and Pull Requests with full history')
  lines.push('- ✅ Comments, reactions, and timeline events')
  lines.push('- ✅ Reviews, commits, and patches for PRs')
  lines.push('- ✅ Discussions with categories and replies')
  lines.push('- ✅ Wiki pages')
  lines.push('- ✅ Releases and tags')
  lines.push('- ✅ Merge queue state')
  lines.push('- ✅ Recent workflow runs')
  lines.push('- ✅ Repository metadata and configuration')
  lines.push('- ✅ Labels, milestones, and CODEOWNERS\n')
  lines.push('Generated by [ghfs](https://github.com/antfu/ghfs)')

  const indexPath = join(dir, 'INDEX.md')
  await writeFile(indexPath, lines.join('\n'), 'utf8')
}
