// @ts-nocheck
import type { RepositoryProvider } from '../types/provider'
import { vi } from 'vitest'

export function createMockProvider(overrides: Partial<RepositoryProvider> = {}): RepositoryProvider {
  return {
    async* paginateItems() {
      yield []
    },
    fetchItems: vi.fn(async () => []),
    async* eachItem() {
    },
    fetchItemsByNumbers: vi.fn(async () => []),
    fetchComments: vi.fn(async () => []),
    fetchPullMetadata: vi.fn(async () => ({
      isDraft: false,
      merged: false,
      mergedAt: null,
      baseRef: 'main',
      headRef: 'feature',
      requestedReviewers: [],
    })),
    fetchPullPatch: vi.fn(async () => ''),
    fetchPullCommits: vi.fn(async () => []),
    fetchReviewComments: vi.fn(async () => []),
    fetchTimeline: vi.fn(async () => []),
    fetchItemSnapshot: vi.fn(async number => ({
      number,
      kind: 'issue' as const,
      updatedAt: '2026-01-01T00:00:00.000Z',
    })),
    fetchRepository: vi.fn(async () => ({
      name: 'repo',
      full_name: 'owner/repo',
      description: null,
      private: false,
      archived: false,
      default_branch: 'main',
      html_url: 'https://github.com/owner/repo',
      fork: false,
      open_issues_count: 0,
      stargazers_count: 0,
      watchers_count: 0,
      forks_count: 0,
      has_issues: true,
      has_projects: true,
      has_wiki: false,
      created_at: '2026-01-01T00:00:00.000Z',
      updated_at: '2026-01-01T00:00:00.000Z',
      pushed_at: '2026-01-01T00:00:00.000Z',
      owner: {
        login: 'owner',
      },
    })),
    fetchRepositoryLabels: vi.fn(async () => []),
    fetchRepositoryMilestones: vi.fn(async () => []),
    fetchAuthenticatedUser: vi.fn(async () => null),
    countUpdatedSince: vi.fn(async () => ({ issues: 0, pulls: 0 })),
    getRequestCount: vi.fn(() => 0),
    actionClose: vi.fn(async () => {}),
    actionReopen: vi.fn(async () => {}),
    actionSetTitle: vi.fn(async () => {}),
    actionSetBody: vi.fn(async () => {}),
    actionAddComment: vi.fn(async () => {}),
    actionAddLabels: vi.fn(async () => {}),
    actionRemoveLabels: vi.fn(async () => {}),
    actionSetLabels: vi.fn(async () => {}),
    actionAddAssignees: vi.fn(async () => {}),
    actionRemoveAssignees: vi.fn(async () => {}),
    actionSetAssignees: vi.fn(async () => {}),
    actionSetMilestone: vi.fn(async () => {}),
    actionClearMilestone: vi.fn(async () => {}),
    actionLock: vi.fn(async () => {}),
    actionUnlock: vi.fn(async () => {}),
    actionRequestReviewers: vi.fn(async () => {}),
    actionRemoveReviewers: vi.fn(async () => {}),
    actionMarkReadyForReview: vi.fn(async () => {}),
    actionConvertToDraft: vi.fn(async () => {}),
    actionApprove: vi.fn(async () => {}),
    actionRequestChanges: vi.fn(async () => {}),
    actionReviewComment: vi.fn(async () => {}),
    actionMerge: vi.fn(async () => {}),
    actionEnqueueMerge: vi.fn(async () => {}),
    actionAddReaction: vi.fn(async () => {}),
    actionRemoveReaction: vi.fn(async () => {}),
    fetchViewerReactions: vi.fn(async () => []),
    fetchWorkflows: vi.fn(async () => []),
    fetchWorkflowRuns: vi.fn(async () => []),
    fetchWorkflowRunAttempts: vi.fn(async () => 1),
    fetchWorkflowRunJobs: vi.fn(async () => []),
    fetchWorkflowRunArtifacts: vi.fn(async () => []),
    fetchWorkflowRunLogs: vi.fn(async () => ''),
    fetchJobLogs: vi.fn(async () => ''),
    fetchRepositoryArtifacts: vi.fn(async () => []),
    fetchOidcSubjectClaim: vi.fn(async () => ({ repository: 'owner/repo' })),
    fetchEnvironmentSecrets: vi.fn(async () => []),
    fetchRepositorySecrets: vi.fn(async () => []),
    fetchRequiredWorkflows: vi.fn(async () => []),
    fetchSelfHostedRunners: vi.fn(async () => []),
    fetchReusableWorkflowUsage: vi.fn(async () => []),
    ...overrides,
  }
}
