import { NodeContext } from '@effect/platform-node'
import { Layer } from 'effect'
import {
  ApplyEngine,
  ExecutionEngine,
  GhfsConfig,
  GitHubClient,
  GitHubResolver,
  MirrorFs,
  SyncCache,
  SyncConcurrency,
  SyncEngine,
  SyncEngineStreaming,
  SyncLabels,
  SyncMilestones,
  SyncComments,
  SyncTimeline,
  SyncReleases,
  SyncDiscussions,
  SyncWiki,
  SyncWorkflows,
  SyncMergeQueue,
  SyncPackages,
  SyncPeople,
  SyncTeams,
  SyncCollaborators,
  SyncCodeowners,
  SyncProjectsV2,
} from '../services'

/** AppLayer @ tip 200cc0f (#198 Schema-first execute.md).
 * Adds SyncLabels / SyncMilestones / SyncComments / SyncTimeline / SyncReleases / SyncDiscussions / SyncWiki / SyncWorkflows / SyncMergeQueue / SyncPackages / SyncPeople / SyncTeams / SyncCollaborators / SyncCodeowners / SyncProjectsV2 — no service body rewrites.
 */
export const AppLayer = Layer.mergeAll(
  GhfsConfig.layer,
  GitHubClient.layer,
  MirrorFs.layer,
  SyncEngine.layer,
  ExecutionEngine.layer,
  ApplyEngine.layer,
  GitHubResolver.layer,
  SyncCache.layer,
  SyncConcurrency.layer,
  SyncEngineStreaming.layer,
  SyncLabels.layer,
  SyncMilestones.layer,
  SyncComments.layer,
  SyncTimeline.layer,
  SyncReleases.layer,
  SyncDiscussions.layer,
  SyncWiki.layer,
  SyncWorkflows.layer,
  SyncMergeQueue.layer,
  SyncPackages.layer,
  SyncPeople.layer,
  SyncTeams.layer,
  SyncCollaborators.layer,
  SyncCodeowners.layer,
  SyncProjectsV2.layer,
  NodeContext.layer,
)
